### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by LazzaAU** [Dirk-Sandberg/FirebaseLoginScreen#10]
Hi There. This code looks perfect for what i'm after. However, i cant get it to run, just wondering if somethings changed that needs updated ? 

I have :
1. pip installed this repo
2. added my firebase API to the kv file
3. used the main.py and main.kv from the examples folder
4. placed a copy of background.jpg in the root directory next to main.py

The errors i get are -
1. At first it was just a blank white screen and noting loaded

2. then i uninstalled everthing and tried again with the above steps in case i did something wrong
and now i get 
>[INFO   ] [Logger      ] Record log in /home/larry/.kivy/logs/kivy_22-10-07_58.txt
[INFO   ] [Kivy        ] v2.1.0
[INFO   ] [Kivy        ] Installed at "/home/larry/Documents/GitHubProjectFiles/AndroidApp/venv/lib/python3.8/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.8.14 (default, Sep  8 2022, 00:02:07) 
[GCC 11.2.0]
[INFO   ] [Python      ] Interpreter at "/home/larry/Documents/GitHubProjectFiles/AndroidApp/venv/bin/python"
[INFO   ] [Logger      ] Purge log fired. Processing...
[INFO   ] [Logger      ] Purge finished!
[INFO   ] [KivyMD      ] 1.0.2, git-38fe356, 2022-08-11 (installed at "/home/larry/Documents/GitHubProjectFiles/AndroidApp/venv/lib/python3.8/site-packages/kivymd/__init__.py")
[INFO   ] [Factory     ] 189 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'3.1 Mesa 22.0.5'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel'>
[INFO   ] [GL          ] OpenGL renderer <b'Mesa Intel(R) HD Graphics 4000 (IVB GT2)'>
[INFO   ] [GL          ] OpenGL parsed version: 3, 1
[INFO   ] [GL          ] Shading version <b'1.40'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [GL          ] NPOT texture support is available
 Traceback (most recent call last):
   File "/home/larry/Documents/GitHubProjectFiles/AndroidApp/main.py", line 14, in <module>
     MainApp().run()
   File "/home/larry/Documents/GitHubProjectFiles/AndroidApp/venv/lib/python3.8/site-packages/kivy/app.py", line 954, in run
     self._run_prepare()
   File "/home/larry/Documents/GitHubProjectFiles/AndroidApp/venv/lib/python3.8/site-packages/kivy/app.py", line 923, in _run_prepare
     self.load_kv(filename=self.kv_file)
   File "/home/larry/Documents/GitHubProjectFiles/AndroidApp/venv/lib/python3.8/site-packages/kivy/app.py", line 696, in load_kv
     root = Builder.load_file(rfilename)
   File "/home/larry/Documents/GitHubProjectFiles/AndroidApp/venv/lib/python3.8/site-packages/kivy/lang/builder.py", line 305, in load_file
     return self.load_string(data, **kwargs)
   File "/home/larry/Documents/GitHubProjectFiles/AndroidApp/venv/lib/python3.8/site-packages/kivy/lang/builder.py", line 407, in load_string
     self._apply_rule(
   File "/home/larry/Documents/GitHubProjectFiles/AndroidApp/venv/lib/python3.8/site-packages/kivy/lang/builder.py", line 660, in _apply_rule
     child.apply_class_lang_rules(
   File "/home/larry/Documents/GitHubProjectFiles/AndroidApp/venv/lib/python3.8/site-packages/kivy/uix/widget.py", line 470, in apply_class_lang_rules
     Builder.apply(
   File "/home/larry/Documents/GitHubProjectFiles/AndroidApp/venv/lib/python3.8/site-packages/kivy/lang/builder.py", line 540, in apply
     self._apply_rule(
   File "/home/larry/Documents/GitHubProjectFiles/AndroidApp/venv/lib/python3.8/site-packages/kivy/lang/builder.py", line 662, in _apply_rule
     self._apply_rule(
   File "/home/larry/Documents/GitHubProjectFiles/AndroidApp/venv/lib/python3.8/site-packages/kivy/lang/builder.py", line 660, in _apply_rule
     child.apply_class_lang_rules(
   File "/home/larry/Documents/GitHubProjectFiles/AndroidApp/venv/lib/python3.8/site-packages/kivy/uix/widget.py", line 470, in apply_class_lang_rules
     Builder.apply(
   File "/home/larry/Documents/GitHubProjectFiles/AndroidApp/venv/lib/python3.8/site-packages/kivy/lang/builder.py", line 540, in apply
     self._apply_rule(
   File "/home/larry/Documents/GitHubProjectFiles/AndroidApp/venv/lib/python3.8/site-packages/kivy/lang/builder.py", line 662, in _apply_rule
     self._apply_rule(
   File "/home/larry/Documents/GitHubProjectFiles/AndroidApp/venv/lib/python3.8/site-packages/kivy/lang/builder.py", line 620, in _apply_rule
     cls = Factory_get(cname)
   File "/home/larry/Documents/GitHubProjectFiles/AndroidApp/venv/lib/python3.8/site-packages/kivy/factory.py", line 147, in __getattr__
     raise FactoryException('Unknown class <%s>' % name)
 kivy.factory.FactoryException: Unknown class \<MDToolbar\>

I'm a noob to Kivy programming but i have spent probably around 4 hours on my own trying to work out what's wrong but i'm stuck.

Any help appreciated as i think this looks awesome

**Comment by LazzaAU** [comment]
Eventually i got it to work. For what ever reason i had to delete the "MDToolbar: " block from two of your files and it all started working properly. Thanks for the repo, its awesome :)
