### ISSUE TITLE
Crash on Android after UrlRequest call

### ISSUE THREAD

**Issue by vise-al** [Dirk-Sandberg/FirebaseLoginScreen#2]
I have been testing this code (great one by the way!) on both Ubuntu and Android. On Ubuntu, everything works fine, but on Android the app crashes.

After doing some research, I realized this happens after the UrlRequest call. In fact, I replaced the UrlRequest by a requests.post and it works fine.

I hope you can help me.

```
06-09 19:12:37.296 22737 22764 I python  : Looking for a refresh token in: /data/user/0/org.test.myapp/files/refresh_token.txt
06-09 19:12:37.302 22737 22764 I python  : [WARNING] [Base        ] Unknown <android> provider
06-09 19:12:37.303 22737 22764 I python  : [INFO   ] [Base        ] Start application main loop
06-09 19:12:42.038 22737 22764 I python  : Attempting to sign user in:   
06-09 19:12:42.563 22737 22764 I python  : {'error': {'code': 400, 'message': 'INVALID_EMAIL', 'errors': [{'message': 'INVALID_EMAIL', 'domain': 'global', 'reason': 'invalid'}]}}
06-09 19:12:42.565 22737 22764 I python  : Couldn't sign the user in:  {'error': {'code': 400, 'message': 'INVALID_EMAIL', 'errors': [{'message': 'INVALID_EMAIL', 'domain': 'global', 'reason': 'invalid'}]}}
06-09 19:12:42.649 22737 22764 I python  : [INFO   ] [Base        ] Leaving application in progress...
06-09 19:12:42.650 22737 22764 I python  :  Traceback (most recent call last):
06-09 19:12:42.650 22737 22764 I python  :    File "/home/vise_al/PycharmProjects/climb-logger/.buildozer/android/app/main.py", line 268, in <module>
06-09 19:12:42.652 22737 22764 I python  :    File "/home/vise_al/PycharmProjects/climb-logger/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/app.py", line 855, in run
06-09 19:12:42.653 22737 22764 I python  :    File "/home/vise_al/PycharmProjects/climb-logger/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/base.py", line 504, in runTouchApp
06-09 19:12:42.655 22737 22764 I python  :    File "/home/vise_al/PycharmProjects/climb-logger/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/core/window/window_sdl2.py", line 747, in mainloop
06-09 19:12:42.656 22737 22764 I python  :    File "/home/vise_al/PycharmProjects/climb-logger/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/core/window/window_sdl2.py", line 479, in _mainloop
06-09 19:12:42.657 22737 22764 I python  :    File "/home/vise_al/PycharmProjects/climb-logger/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/base.py", line 339, in idle
06-09 19:12:42.658 22737 22764 I python  :    File "/home/vise_al/PycharmProjects/climb-logger/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/clock.py", line 591, in tick
06-09 19:12:42.660 22737 22764 I python  :    File "kivy/_clock.pyx", line 384, in kivy._clock.CyClockBase._process_events
06-09 19:12:42.661 22737 22764 I python  :    File "kivy/_clock.pyx", line 414, in kivy._clock.CyClockBase._process_events
06-09 19:12:42.662 22737 22764 I python  :    File "kivy/_clock.pyx", line 412, in kivy._clock.CyClockBase._process_events
06-09 19:12:42.664 22737 22764 I python  :    File "kivy/_clock.pyx", line 154, in kivy._clock.ClockEvent.tick
06-09 19:12:42.665 22737 22764 I python  :    File "kivy/_clock.pyx", line 86, in kivy._clock.ClockEvent.get_callback
06-09 19:12:42.666 22737 22764 I python  :    File "/home/vise_al/PycharmProjects/climb-logger/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/weakmethod.py", line 56, in is_dead
06-09 19:12:42.668 22737 22764 I python  :  ReferenceError: weakly-referenced object no longer exists
06-09 19:12:42.668 22737 22764 I python  : Python for android ended.
```

**Comment by Dirk-Sandberg** [comment]
Oops, didn't get notified of this issue, sorry for the late response. I believe the `ReferenceError` is a bug in the default version of Kivy that Buildozer uses right now. Can you try specifying `kivy==2.0.0rc1` in the `requirements` line of your `buildozer.spec` file?
